<template>
  <section>
    <div class="w-100 pt-80 black-layer pb-70 opc65 position-relative">
      <div class="fixed-bg" :style="`background-image: url(require('@/assets/images/page-title-bg.jpg'))`"></div>
      <div class="container">
        <div class="page-title-wrap text-center w-100">
          <div class="page-title-inner d-inline-block">
            <h1 class="mb-0">JUDGE</h1>
            <ol class="breadcrumb mb-0">
              <!--                  <li class="breadcrumb-item">SAFIU WAHEED</li>-->
              <!--                  <li class="breadcrumb-item active">Modrasha</li>-->
            </ol>
          </div>
        </div><!-- Page Title Wrap -->
      </div>
    </div>
  </section>
  <section >
    <div class="w-100 pt-120 pb-280 position-relative">
      <img class="sec-botm-rgt-mckp img-fluid position-absolute" :src="require('@/assets/images/sec-botm-mckp.png')" alt="Sec Bottom Mockup">
      <div class="container-fluid px-5">
        <div class="serv-wrap wide-sec">
          <div class="row px-5 justify-content-center flex-row-reverse mrg10">
            <div class=" col-md-6 col-sm-6 col-lg-3"  v-for="({chapter, verse, preview}, i) in questions" :key="i" @click="() => sendRange(el)">
              <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" :style="`background-image: url(${require('@/assets/images/pattern-bg.jpg')})`">
                <i class="flaticon-quran thm-clr"></i>
                <h3 class="mb-2">{{`Q${chapter}:${verse}`}}</h3>
                <div class="d-flex justify-content-between">
                  <p style="font-family: uthmani; font-size: 24px; line-height: 2" class="alignright" v-html="preview[0]['text_uthmani_tajweed'].replace('tajweed', 'span')"></p>
                </div>
              </div>
            </div>

          </div>
        </div><!-- Services Wrap -->
      </div>
    </div>
  </section>
<!--    <div class="container-fluid ">-->
<!--         <h3 class="mt-2">Questions Generated by Participant</h3>-->
<!--         <p class=" text-center text-danger">Judge Screen</p>-->
<!--         <div class="row flex-row-reverse">-->
<!--            <div class="questions col-md-3 col-sm-6 my-4" v-for="({chapter, verse, preview}, i) in questions" :key="i">-->
<!--             <div class="card h-100">-->
<!--                <div class="card-header bg-primary text-white">-->
<!--                    <h5 class="card-title">Question {{i + 1}}</h5>-->
<!--                </div>-->
<!--                <div class="card-body">-->
<!--                    <p class="card-text">{{`Q${chapter}-${verse}`}}</p>-->
<!--                    <p style="font-family: uthmani" class="alignright" v-html="preview[0]['text_uthmani_tajweed']"></p>-->
<!--                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
<!--                </div>-->
<!--            </div>-->
<!--         </div>-->
<!--         </div>-->
<!--        -->
<!--        &lt;!&ndash; <button class="btn btn-success btn-lg" @click="generateQuestion">Generate</button>  &ndash;&gt;-->
<!--    </div>-->
</template>

<script>
import io from 'socket.io-client'
// import axios from 'axios'

export default {
   name: 'ModeratorPage',
   data () {
       return {
           questions: [],
           chapters: [],
           socket: io('localhost:9090')
       }
   },

    mounted () {
            this.$nextTick(async function() {
                this.socket.emit("JUDGES", {room: "room2"})
                this.socket.on('GENERATE_QUESTION', question => {
                  this.questions = question.message
                  this.$store.dispatch('getChapters', question.message)
                  this.chapters = this.$store.state.chapters
                });

            })
        
    }
}
</script>
<style scoped>
@font-face {
  font-family: uthmani;
  src: url("@/assets/UthmanicHafs1Ver18.woff2");
}
</style>
